default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres  # changed from password to postgres
  pool: 5

development:
  <<: *default
  database: pet-service_development


test:
  <<: *default
  database: pet-service_test