default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres # change from password when merge
  pool: 5

development:
  <<: *default
  database: tinder

test:
  <<: *default
  database: pet-service_test
